//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventeam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int PortfolioID { get; set; }
        public string ProjectName { get; set; }
        public int FormatID { get; set; }
        public string Сustomer { get; set; }
        public string Participants { get; set; }
        public string Location { get; set; }
        public string Task { get; set; }
        public string Implementation { get; set; }
        public string Result { get; set; }
    
        public virtual Format Format { get; set; }
    }
}
