//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventeam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomID { get; set; }
        public int HotelID { get; set; }
        public string Name { get; set; }
        public int RoomCategoryID { get; set; }
        public int RoomTypeID { get; set; }
        public int Quantity { get; set; }
    
        public virtual RoomCategory RoomCategory { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
